[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = ["CLKuuu"]

[tool.poetry.dependencies]
python = "^3.11"
discord.py = "^2.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
